# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """$directory $all\n$character""" # A minimal left prompt
palette = "catppuccin_mocha" # colorscheme

# A continuation prompt that displays two filled-in arrows
continuation_prompt = '▶▶ '


[directory]
truncate_to_repo = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red) '

[line_break]
disabled = true

[package]
disabled = true

[cmd_duration]
min_time = 5000
format = 'took [$duration](bold yellow) '

[git_branch]
format =  '[$symbol$branch](bold gray) '
symbol = " "

[git_status]
disabled = true

[lua]
format = '[$symbol](bold purple)'
symbol = " "

[nodejs]
format = '[$symbol](bold green)'
symbol = " "

[php]
format = '[$symbol](bold 147)'
symbol = " "




[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
